package blog.anirbanm.googlehr.model.vo;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;

import oracle.jbo.Key;
import oracle.jbo.RangePagingDataFilter;
import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 05 01:12:45 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesPVOImpl extends ProgrammaticViewObjectImpl {
    
    private HashMap<String, Object> employees;
    
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesPVOImpl() {
    }

    /**
     * getRangePagingData - for custom java data source support.
     */
    public Collection<Object> getRangePagingData(RangePagingDataFilter filter) {
        Collection<Object> value = super.getRangePagingData(filter);
        return value;
    }

    /**
     * retrieveDataByKey - for custom java data source support.
     */
    public Collection<Object> retrieveDataByKey(Key key, int size) {
        Collection<Object> value = super.retrieveDataByKey(key, size);
        return value;
    }

    /**
     * getScrollableData - for custom java data source support.
     */
    public Collection<Object> getScrollableData(ScrollableDataFilter filter) {
        ArrayList<Object> rows = new ArrayList<Object>();
        final TreeMap<String, Object> employees = new TreeMap<String, Object>(getEmployees());
        if (employees != null) {
            for (Map.Entry employee : employees.entrySet()) {
                rows.add(employee.getValue());
            }
        }
        return rows;
    }

    public void setEmployees(HashMap<String, Object> employees) {
        this.employees = employees;
    }

    public HashMap<String, Object> getEmployees() {
        return employees;
    }
}

