package blog.anirbanm.googlehr.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 30 18:42:05 IST 2018
// ---------------------------------------------------------------------
public interface GoogleHrModule extends ApplicationModule {
    void initDepartments();

    void onDepartmentSelection();
}

